config/routes.rb
Phonebook::Application.routes.draw do
  get "phone/index"

  get "phone/newphone"
  get "phone/edit/:id" => "phone#edit"
  get "phone/del/:id" => "phone#del"

  post "phone/create"
  put "phone/updateing/:id" => "phone#updateing"
  put "phone/destoring/:id" => "phone#destoring"

   match ':controller(/:action(/:id(.:format)))'
end

app/models/pbook.rb
class Pbook < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/phone_controller.rb
class PhoneController < ApplicationController
  def index
    @phones = Pbook.all
  end

  def newphone
    @pbook = Pbook.new
  end

  def create
    @pbook = Pbook.new(params[:pbook])
    @pbook.save
    redirect_to :action => :index
  end

  def edit
    @pbook = Pbook.find(params[:id])
  end

  def updateing
    @pbook = Pbook.find(params[:id])
    @pbook.update_attributes(params[:pbook])

    redirect_to :action => "index"
  end

  def del
    @pbook = Pbook.find(params[:id])
    @pbook.destroy

    redirect_to :action => "index"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/phone_helper.rb
module PhoneHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Phonebook</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/phone/edit.html.erb
<h1>add new phone number</h1>
<%= form_for @pbook, :url => {:controler => "phone", :action => "updateing"} do |f| %>

<div class = "field">
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>
<div class = "field">
  <%= f.label :phone %>
  <%= f.text_field :phone %>
</div>
<div class = "field">
  <%= f.label :birthday %>
  <%= f.text_field :birthday %>
</div>
<div class = "field">
  <%= f.submit %>
</div>
<% end %>
<p><%= link_to "Back", phone_index_path %></p>

app/views/phone/index.html.erb
<h1>Phonebook</h1>
<p>
<% @phones.each do |p|%>
<ul>
  <li><%= p.name %></li>
  <li><%= p.phone %></li> 
  <li><%= p.birthday %></li>
  <li><%= link_to "edit", :action => "edit", :id => p %></li>
</ul>
<% end %>
<p><%= link_to "add new phone number", phone_newphone_path %></p>
</p>

app/views/phone/modify.html.erb
<h1>add new phone number</h1>
<%= form_for @pbook, :url => {:controler => "phone", :action => "updateing"} do |f| %>

<div class = "field">
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>
<div class = "field">
  <%= f.label :phone %>
  <%= f.text_field :phone %>
</div>
<div class = "field">
  <%= f.label :birthday %>
  <%= f.text_field :birthday %>
</div>
<div class = "field">
  <%= f.submit %>
</div>
<% end %>
<p><%= link_to "Back", phone_index_path %></p>

app/views/phone/newphone.html.erb
<h1>add new phone number</h1>
<%= form_for @pbook, :url => {:controler => "phone", :action => "create"} do |f| %>

<div class = "field">
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>
<div class = "field">
  <%= f.label :phone %>
  <%= f.text_field :phone %>
</div>
<div class = "field">
  <%= f.label :birthday %>
  <%= f.text_field :birthday %>
</div>
<div class = "field">
  <%= f.submit %>
</div>
<% end %>
<p><%= link_to "Back", phone_index_path %></p>